<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'App\\Middleware\\ApiAuthentication' => 'get1',
  'subEntry1' => 'get2',
  'subEntry2' => 'get3',
  'subEntry3' => 'get4',
  'subEntry4' => 'get5',
  'App\\Routing\\ApiRouteResolver' => 'get6',
  'subEntry5' => 'get7',
  'App\\Entity\\Auth\\IdentityStorage' => 'get8',
  'App\\Entity\\Register\\UserEntity' => 'get9',
  'App\\Repository\\RepositoryManager' => 'get10',
  'subEntry6' => 'get11',
  'App\\Service\\Auth\\AccessTokenService' => 'get12',
  'subEntry7' => 'get13',
  'subEntry8' => 'get14',
  'subEntry9' => 'get15',
  'App\\Service\\Auth\\ClientService' => 'get16',
  'subEntry10' => 'get17',
  'App\\Service\\Register\\UserService' => 'get18',
  'subEntry11' => 'get19',
  'Slim\\Flash\\Messages' => 'get20',
  'Psr\\Log\\LoggerInterface' => 'get21',
  'League\\OAuth2\\Server\\AuthorizationServer' => 'get22',
  'SlashTrace\\SlashTrace' => 'get23',
  'Symfony\\Component\\Translation\\Translator' => 'get24',
  'Slim\\Views\\Twig' => 'get25',
  'Illuminate\\Database\\ConnectionInterface' => 'get26',
  'App\\Service\\RouteFinder' => 'get27',
  'subEntry12' => 'get28',
  'subEntry13' => 'get29',
);

    protected function get2()
    {
        return $this->delegateContainer->get('App\\Service\\RouteFinder');
    }

    protected function get3()
    {
        return $this->delegateContainer->get('App\\Routing\\ApiRouteResolver');
    }

    protected function get4()
    {
        return $this->delegateContainer->get('App\\Entity\\Auth\\IdentityStorage');
    }

    protected function get5()
    {
        return $this->delegateContainer->get('App\\Repository\\RepositoryManager');
    }

    protected function get1()
    {
        $object = new App\Middleware\ApiAuthentication($this->get2(), $this->get3(), $this->get4(), $this->get5());
        return $object;
    }

    protected function get7()
    {
        return $this->delegateContainer->get('Psr\\Container\\ContainerInterface');
    }

    protected function get6()
    {
        $object = new App\Routing\ApiRouteResolver($this->get7());
        return $object;
    }

    protected function get8()
    {
        $object = new App\Entity\Auth\IdentityStorage();
        return $object;
    }

    protected function get9()
    {
        $object = new App\Entity\Register\UserEntity([
        ]);
        return $object;
    }

    protected function get11()
    {
        return $this->delegateContainer->get('Illuminate\\Database\\ConnectionInterface');
    }

    protected function get10()
    {
        $object = new App\Repository\RepositoryManager($this->get11());
        return $object;
    }

    protected function get13()
    {
        return $this->delegateContainer->get('App\\Repository\\RepositoryManager');
    }

    protected function get14()
    {
        return $this->delegateContainer->get('App\\Service\\Auth\\ClientService');
    }

    protected function get15()
    {
        return $this->delegateContainer->get('App\\Service\\Register\\UserService');
    }

    protected function get12()
    {
        $object = new App\Service\Auth\AccessTokenService($this->get13());
        \DI\Definition\Resolver\ObjectCreator::setPrivatePropertyValue(NULL, $object, 'clientService', $this->get14());
        \DI\Definition\Resolver\ObjectCreator::setPrivatePropertyValue(NULL, $object, 'userService', $this->get15());
        return $object;
    }

    protected function get17()
    {
        return $this->delegateContainer->get('App\\Repository\\RepositoryManager');
    }

    protected function get16()
    {
        $object = new App\Service\Auth\ClientService($this->get17());
        return $object;
    }

    protected function get19()
    {
        return $this->delegateContainer->get('App\\Repository\\RepositoryManager');
    }

    protected function get18()
    {
        $object = new App\Service\Register\UserService($this->get19());
        return $object;
    }

    protected function get20()
    {
        $object = new Slim\Flash\Messages(NULL, NULL);
        return $object;
    }

    protected function get21()
    {
        return $this->resolveFactory([
            0 => 'App\\Factory\\MonologFactory',
            1 => 'create',
        ], 'Psr\\Log\\LoggerInterface');
    }

    protected function get22()
    {
        return $this->resolveFactory([
            0 => 'App\\Factory\\AuthorizationServerFactory',
            1 => 'create',
        ], 'League\\OAuth2\\Server\\AuthorizationServer');
    }

    protected function get23()
    {
        return $this->resolveFactory([
            0 => 'App\\Factory\\SlashTraceFactory',
            1 => 'create',
        ], 'SlashTrace\\SlashTrace');
    }

    protected function get24()
    {
        return $this->resolveFactory([
            0 => 'App\\Factory\\TranslatorFactory',
            1 => 'create',
        ], 'Symfony\\Component\\Translation\\Translator');
    }

    protected function get25()
    {
        return $this->resolveFactory([
            0 => 'App\\Factory\\TwigFactory',
            1 => 'create',
        ], 'Slim\\Views\\Twig');
    }

    protected function get26()
    {
        return $this->resolveFactory([
            0 => 'App\\Factory\\DbConnectionFactory',
            1 => 'create',
        ], 'Illuminate\\Database\\ConnectionInterface');
    }

    protected function get28()
    {
        return $this->delegateContainer->get('Slim\\Interfaces\\RouteResolverInterface');
    }

    protected function get29()
    {
        return $this->delegateContainer->get('Slim\\Interfaces\\RouteCollectorInterface');
    }

    protected function get27()
    {
        $object = new App\Service\RouteFinder($this->get28(), $this->get29());
        return $object;
    }

}
